//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int RoleID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string RoleName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> CanManageDatabase { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
