//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ServiceID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public string Name { get; internal set; }
        public string ServicesName { get; internal set; }
    }
}
